qkd/accounts/urls.py
from django.conf.urls import url
from django.urls import path,include
from .views import registerview
from .views import loginview,logoutview,chat,reviews,decrypt
app_name='accounts'

urlpatterns = [
    path(r'register/', registerview, name="register"),
    path(r'login/', loginview, name="login"),
    path(r'logout/', logoutview, name="logout"),
    path(r'<s_idx>/<r_idx>/chat/', chat, name="chat"),
    path(r'<id>/<idx>/<add>/reviews/', reviews, name="reviews"),
    path(r'<id>/<idx>/<info>/<r_idx>/decrypt/', decrypt, name="decrypt"),
   


]

qkd/qkd/urls.py
from django.contrib import admin
from accounts.views import func
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path(r'', func, name="home"),
    path(r'accounts/', include('accounts.urls', namespace="accounts")),
]

urlpatterns = urlpatterns + static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

qkd/accounts/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class secret_keys_receiver(models.Model):
	receiver_key = models.CharField(max_length=1000)
	
class secret_keys(models.Model):
	sender_key = models.CharField(max_length=1000)
	r_index = models.OneToOneField(secret_keys_receiver, on_delete=models.CASCADE,default=True)


	

class Profile(models.Model):
	
	user = models.OneToOneField(User, on_delete=models.CASCADE, null=True)
	address = models.CharField(max_length=30)
	mobile = models.CharField(max_length=13)
	gender = models.CharField(max_length=6)
	joined_date = models.DateTimeField(auto_now=True, auto_now_add=False, null=True)


	def __str__(self):
		return self.address

	def __unicode__(self):
		return self.address

class Messages(models.Model):
	sender = models.CharField(max_length=30)
	receiver = models.CharField(max_length=30)
	s_msg_body = models.CharField(max_length=250)
	r_msg_body = models.CharField(max_length=500, default="")
	seen = models.BooleanField(default=False)
	date_time = models.DateTimeField(auto_now=False,auto_now_add=True, null=True)
	index = models.IntegerField(max_length=10,default=0)
	

	def __str__(self):
		return str(self.id)

qkd/accounts/forms.py
from django.contrib.auth import authenticate
from django.contrib.auth.models import User
from django import forms
from .models import Profile

GENDER_CHOICES = [('Male','Male'), ('Female','Female'), ('Others','Others')]

class RegistrationForm(forms.Form):

	first_name = forms.CharField(label="", widget=forms.TextInput(attrs={'autofocus':'on', 'autocomplete':'off', 'class':'form-control', 'placeholder':'First Name'}))
	last_name = forms.CharField(label="", widget=forms.TextInput(attrs={'autocomplete':'off','class':'form-control', 'placeholder':'Surname'}))
	# reg = forms.CharField(label="", widget=forms.TextInput(attrs={'autocomplete':'off','class':'form-control', 'placeholder':'Registration Number'}))
	#dob = forms.DateField(label="Date of birth", widget=forms.DateInput(attrs={'autocomplete':'off','class':'form-control', 'placeholder':'YYYY-MM-DD'}))
	#gender = forms.CharField(label='Gender', widget=forms.RadioSelect(choices=GENDER_CHOICES, attrs={'class':'custom-control-inline'}))
	gender= forms.CharField(label='Gender', widget=forms.Select(choices=GENDER_CHOICES))
	address = forms.CharField(label="", widget=forms.TextInput(attrs={'autocomplete':'off','class':'form-control', 'placeholder':'address'}))
	# college= forms.CharField(label='College', widget=forms.Select(choices=COLLEGE_CHOICES))
	mobile = forms.CharField(label="", widget=forms.TextInput(attrs={'autocomplete':'off','class':'form-control', 'placeholder':'Mobile Number'}))
	email = forms.CharField(label="", widget=forms.EmailInput(attrs={'autocomplete':'off','class':'form-control', 'placeholder':'Email address'}))
	username = forms.CharField(label="", widget=forms.TextInput(attrs={'autocomplete':'off','class':'form-control', 'placeholder':'Username'}))
	password = forms.CharField(label="", widget=forms.PasswordInput(attrs={'autocomplete':'off','class':'form-control', 'placeholder':'Your Password'}))
	cpassword = forms.CharField(label="", widget=forms.PasswordInput(attrs={'autocomplete':'off','class':'form-control', 'placeholder':'Confirm Password'}))
	
	def clean_email(self):
		email = self.cleaned_data.get("email")
		if len(User.objects.filter(email=email)):
			raise forms.ValidationError("Email Already Registered")

		return email


	def clean_mobile(self):
		mobile = self.cleaned_data.get("mobile")
		try:
			a = int(mobile)
		except:
			raise forms.ValidationError("Incorrect mobile number")
		if len(mobile)!=10:
			raise forms.ValidationError("Incorrect mobile number")
		elif len(Profile.objects.filter(mobile=mobile)):
			raise forms.ValidationError("Mobile Already Registered")

		return mobile

	def clean_username(self):
		username = self.cleaned_data.get("username")
		if len(User.objects.filter(username=username)):
			raise forms.ValidationError("Username already has been taken")

		return username

	def clean_password(self):
		password = self.cleaned_data.get("password")
		if len(password)<6:
			raise forms.ValidationError("Password must be at least 6 characters")

		return password

	def clean_cpassword(self):
		password = self.cleaned_data.get("password")
		cpassword = self.cleaned_data.get("cpassword")
		if password!=cpassword:
			raise forms.ValidationError("Passwords must match")

		return password


class LoginForm(forms.Form):
	username = forms.CharField(label="", widget=forms.TextInput(attrs={'autocomplete':'off','autofocus':'on','class':'form-control', 'placeholder':'Username'}))
	password = forms.CharField(label="", widget=forms.PasswordInput(attrs={'autocomplete':'off','class':'form-control', 'placeholder':'Password'}))

	def clean_username(self):
		username = self.cleaned_data.get("username")
		if len(User.objects.filter(username=username))==0:
			raise forms.ValidationError("Username does not exist")

		return username

	def clean_password(self):
		username = self.cleaned_data.get("username")
		password = self.cleaned_data.get("password")
		user = authenticate(username=username, password=password)
		if user is None:
			raise forms.ValidationError("Wrong Username or Password")
		return password

qkd/accounts/views.py
from django.shortcuts import render,redirect
import time
from numpy import matrix
from math import pow, sqrt
from random import randint
import sys, argparse
from django.urls import reverse
from accounts.quantum_channel import *
from .models import secret_keys,secret_keys_receiver,Messages
from .models import Profile
from .forms import RegistrationForm,LoginForm
from django.contrib.auth.models import User
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect,HttpResponse
from accounts.sender import sender_msg
from accounts.receiver import receiver_msg,receive_msg
from accounts.encrypt_decrypt import *


from django.contrib.auth import (

	authenticate,
	login,
	logout

	)

def loginview(request):
	form = LoginForm(request.POST or None)
	if request.method =="POST":
		if form.is_valid():
			username = form.cleaned_data.get("username")
			password = form.cleaned_data.get("password")
			print(username,password)
			user = authenticate(username=username, password=password)
			login(request, user)
			return HttpResponseRedirect(reverse("home"))

	context = {
		'form':form 
	}
	return render(request, 'accounts/login.html', context)


@login_required
def logoutview(request):
	logout(request)
	return HttpResponseRedirect(reverse('home'))


	

def registerview(request):
	form = RegistrationForm(request.POST or None)
	
	if request.method=="POST":
	
		if form.is_valid():
			first_name = form.cleaned_data.get('first_name')
			last_name= form.cleaned_data.get('last_name')
			address = form.cleaned_data.get("address")
			mobile = form.cleaned_data.get("mobile")
			gender = form.cleaned_data.get("gender")
			email = form.cleaned_data.get('email')
			username = form.cleaned_data.get("username")
			password  = form.cleaned_data.get('password ')
			cpassword  = form.cleaned_data.get('cpassword ')
			
			user, create = User.objects.get_or_create(
			
				first_name=first_name,
				last_name=last_name,
				username=username,
				email=email,

			)
			user.set_password(form.cleaned_data['password'])
			user.save()
			

			pro = Profile(mobile=mobile, address = address , gender=gender, user=user )
			pro.save()

			messages.success(request, "Successfully Saved")
			context={
				"msg":"Successfully Registered!!"
			} 
			
			return render(request,'accounts/messagesdisplay.html',context)
	context = {
		'form':form,
	}
	return render(request, 'accounts/registration.html', context)





def func(request):
	profiles = Profile.objects.all()
	return render(request,'accounts/index.html',{'profiles': profiles })
	




def chat(request,s_idx,r_idx):
	profiles = Profile.objects.all()
	# print(int(s_idx))
	# print(int(r_idx))
	# print(profiles)

	sender = Profile.objects.get(user=s_idx)
	# print(sender)
	receiver = Profile.objects.get(id=r_idx)
	# print(receiver)
	receiver = receiver.user
	sender  = sender.user
	seen = False
	add = 0
	msg = Messages.objects.filter(sender = sender , receiver = receiver)
	r_msg = Messages.objects.filter(sender = receiver , receiver = sender)

	r_name = receiver
	r_seen = False
	r_ex = 0
	if len(r_msg) != 0:
		r_seen = r_msg[0].seen
		r_msg = r_msg[0]
		r_ex = 1

	if len(msg) == 0:
			add = 1
	else:
		msg = msg[0]
		seen = msg.seen
	# print(seen)
	# print(add)
	# print(msg.sender)
	pro = list()
	for i in profiles:
		if i.user != sender:
			pro.append(i)
			
	params = {'profiles':pro,'msg': msg,'add':add,'seen':seen,'idx':r_idx,'r_name':r_name,'r_msg':r_msg,'r_seen':r_seen,'r_ex':r_ex}
	
	return render(request,'accounts/chat.html',params)






def reviews(request,id,idx,add):
	id=int(id)
	# print(id)
	# print(int(idx))
	if request.method == "POST":
		msg = request.POST.get("message")
	print(msg)


	ret = list()
	N = 72
	key = secret_keys_receiver(receiver_key = "" )
	key.save()
	r_idx = key.id
	key = secret_keys(sender_key = "" ,r_index=key)
	key.save()
	s_idx = key.id
	

	
	for i in range (N):
		print ("############# {0} #############".format(str(i)))
		ret.append(QKD(16,s_idx,r_idx,verbose = True ,eve_present = True))
		
		print ("###############################".format(str(i)))
	t = "{0:.2f}".format(float(ret.count(True))*100.0/float(N))
	u = "{0:.2f}".format(float(ret.count(False))*100.0/float(N))
	# print ("True: {0} <{1}%>".format(ret.count(True),str(t)))
	# print ("False: {0} <{1}%>".format(ret.count(False),str(u)))

	print("Exchanged Secret keys")
	key = s_key(s_idx)
	print("Sender's secret key")
	print(key)
	key = r_key(r_idx)
	print("Receiver's secret key")
	print(key)
	sender = Profile.objects.get(user=id)
	# print(sender.user)
	receiver = Profile.objects.get(id=idx)
	# print(receiver.user)
	sender = sender.user
	receiver = receiver.user
	
	add = int(add)
	# print(type(s_idx))

	if add == 1:
		info = Messages(sender = sender, receiver = receiver, s_msg_body = "",r_msg_body="", seen = False,index = s_idx)
		info.save()
		i = info.id
		sender_msg(i,msg)
		
	else:

		info = Messages.objects.filter(sender = sender , receiver = receiver).update( s_msg_body = "",r_msg_body="",seen = False, index = s_idx)
		
		i = info

		sender_msg(i,msg)
	print("Message to send :")
	print(msg)
	msg = encryption(s_idx,msg)
	print("Encrypted Msg : ")
	print(msg)
	
	receive_msg(i,msg)
	info = Messages.objects.filter(sender = sender , receiver = receiver).update(seen = True)
		
	msg = decryption(r_idx,msg)
	print("Decrypted Message :")
	print(msg)

	return redirect('accounts:chat', s_idx= id, r_idx = idx)




def decrypt(request,id,idx,info,r_idx):

	info = Messages.objects.filter(id=info)
	print(info)

	print("hgsahgas")
	msg = decryptin(info)
	print(msg)
	receiver_msg(info,msg)
	for i in info:
		xyz = i.id
		Messages.objects.filter(id=xyz).update(seen = False)
	return redirect('accounts:chat', s_idx= id, r_idx = idx)

qkd/templates/accounts/chat.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    {% load static %}
   
    <title>Secure Communication Using Quantum Key Distribution</title>

    <link rel="stylesheet" type="text/css" href="{% static 'accounts/index.css' %}">
  </head>
  <body>
    <div id="wrapper"style="width: 1350px; margin-left: -10px;" >

      <div id="first" style="margin-top: -200px;width: 1350px;float: left;">
        

        <div id="div11" style="margin-top: 15px;">
        {% if user.is_authenticated %}
        <h1 >HELLO!!  &nbsp;   {{ user.first_name}} </h1>
        <p style="margin-top: 30px;font-size: 1.4em"><i>Communication – the human connection</i></p>
        {% else %}
        <h1 >Secure Communication Using Quantum Key Distribution</h1>
        <p style="margin-top: 30px;font-size: 1.4em"><i>Communication – the human connection</i></p>
        {% endif %}
        </div>
        </div>
      <div id="menu" style="height: 50px;background-color: black;float: left;margin-top: -50px;width: 1350px;">
    <div id="menu4" style="margin-top: 20px;background-color: black; width: 1350px">
      <ul>
      <li><a href="{% url 'home' %}">HOME</a></li>
      {% if user.is_authenticated %}

      {% else %}
      <li><a href="{% url 'accounts:register' %}">SIGN UP</a></li>
      {% endif %}
      {% if user.is_authenticated %}
      <li><a href="{% url 'accounts:logout' %}">LOGOUT</a></li>
      {% else %}
      <li><a href="{% url 'accounts:login' %}">LOGIN</a></li>
      {% endif %}

      </ul>
    </div>
    </div>
      


    <div id = "div21" style="margin-top:200px; width: 1350px;min-height:360px;height:auto;background-color: green;">
    <div id = "content1" style="min-height:360px;height:auto; width: 500px;  float: left;">
      
      {% if user.is_authenticated %}

      <table>
      {% for i in profiles %}
      <a href="{% url 'accounts:chat' user.id i.id%}">
      <button style="width:350px; height: 50px;">
      {{i.user}} </button>
      </a><br/>
      {% endfor %}
        
      </table>

      {% else %}

      {% endif %}
      
    </div>
    <div id ="content2" style="min-height:360px;height:auto; width: 650px;  float: left;">
</h2><br/><br/>
      <h2>{{ r_name}}</h2><br/>
      
      {{r_msg.r_msg_body}}&nbsp;&nbsp;&nbsp;&nbsp;

      {% if r_seen == True %}

      <a href="{% url 'accounts:decrypt' user.id idx r_msg.id r_msg.index %}">Decrypt Message</a>
      {% endif %}
    {% if seen == False %}
      {% if add == 0 %}
      <h3><!-- Sender : {{ msg.sender}} --><br/>
      <!-- Receiver : {{ msg.receiver }} --><br/>
      Message : {{msg.s_msg_body}}<br/></h3>

<form method="post" action="{% url 'accounts:reviews' user.id idx add  %}">{% csrf_token %}
  <h3>Write Message:</h3> <textarea name="message" placeholder="Enter your message here..." style="width:300px; height: 60px;"></textarea>

  <button onclick = "#" style="width:100px; height: 35px; background-color: green">Send Message</button>
</form>


      
    {% else %}

      <form method="post" action="{% url 'accounts:reviews' user.id idx add  %}">{% csrf_token %}
      <h3>Write Message:</h3> <textarea name="message" placeholder="Enter your message here..." style="width:300px; height: 60px;"></textarea>

      <button onclick = "#" style="width:100px; height: 35px; background-color: green">Send Message</button>
      </form>
    {% endif %}
    {% else %}
      <h3><!-- Sender : {{ msg.sender}} --><br/>
      <!-- Receiver : {{ msg.receiver }} --><br/>
      Message : {{msg.s_msg_body}}
      </h3>
      <h4>Message Not Seen Yet!!!</h4>
    {% endif %}

    
    </div>
    </div>



      <div id="footer" style="margin-top: 0px; width:1310px;">
      <p><i><marquee>
      Communication – the human connection – is the key to personal and career success
      &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
      Conversation is king. Content is just something to talk about.
      &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
      <h7>Wise men speak because they have something to say; Fools because they have to say something</h7></i></marquee></p>
      </div>


    </div>
    </body>
</html>

qkd/templates/accounts/chats.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    {% load static %}
   
    <title>NIT REVIEW SYSTEM</title>

    <link rel="stylesheet" type="text/css" href="{% static 'accounts/index.css' %}">
  </head>
  <body>
  	<div id="wrapper" >
  		<div id="first" style="margin-top: -200px">
  			

  			<div id="div11" style="margin-top: 15px;">
				{% if user.is_authenticated %}
				<h1 >HELLO!!  &nbsp;   {{ user.first_name}} </h1>
				<p style="margin-top: 30px;font-size: 1.4em"><i>Rate your college today!</i></p>
				{% else %}
				<h1 >NIT REVIEWS</h1>
				<p style="margin-top: 30px;font-size: 1.4em"><i>Rate your college today!</i></p>
				{% endif %}
  			</div>

  		<div id="menu" style="">
 		<div id="menu4">
			<ul>
			<li><a href="{% url 'home' %}">HOME</a></li>
			{% if user.is_authenticated %}

			<li><a href="#">GIVE REVIEW</a></li>
			{% else %}
			<li><a href="{% url 'accounts:register' %}">SIGN UP</a></li>
			{% endif %}
			{% if user.is_authenticated %}
			<li><a href="{% url 'accounts:logout' %}">LOGOUT</a></li>
			{% else %}
			<li><a href="{% url 'accounts:login' %}">LOGIN</a></li>
			{% endif %}

			</ul>
 		</div>
 		</div>
  		</div>


		<div id = "div21" style="margin-top:190px;background-color: pink;">
		<div id = "content" style="margin-right:100px;height:200px; width: 200px;  margin-top: 100px">
			<center>
			{% if user.is_authenticated %}

			<table>
			{% for i in profiles %}
			<a href="{% url 'accounts:chat' user.id  i.id %}">
			<button style="width:350px; height: 50px;">
			{{i.user}} {{i.id}}</button>
			</a><br/>
			{% endfor %}
				
			</table>

			{% else %}

			{% endif %}
			</center>
		</div>
		<center><h3>{{ r_name}}</h3>
			
			{{r_msg.r_msg_body}}

			{% if r_seen == True %}
			<a href="{% url 'accounts:decrypt' user.id idx r_msg.id r_msg.index %}">Decrypt Message</a>
			{% endif %}
		{% if seen == False %}
			{% if add == 0 %}
			<h3><!-- Sender : {{ msg.sender}} --><br/>
			<!-- Receiver : {{ msg.receiver }} --><br/>
			Message :	{{msg.s_msg_body}}<br/></h3>

<form method="post" action="{% url 'accounts:reviews' user.id idx add  %}">{% csrf_token %}
	<h3>Write Message:</h3> <textarea name="message" placeholder="Enter your message here..." style="width:300px; height: 60px;"></textarea>

	<button onclick = "#" style="width:100px; height: 35px; background-color: green">Send Message</button>
</form>


			
		{% else %}

			<form method="post" action="{% url 'accounts:reviews' user.id idx add  %}">{% csrf_token %}
			<h3>Write Message:</h3> <textarea name="message" placeholder="Enter your message here..." style="width:300px; height: 60px;"></textarea>

			<button onclick = "#" style="width:100px; height: 35px; background-color: green">Send Message</button>
			</form>
		{% endif %}
		{% else %}
			<h3><!-- Sender : {{ msg.sender}} --><br/>
			<!-- Receiver : {{ msg.receiver }} --><br/>
			Message :	{{msg.s_msg_body}}
			</h3>
			<h4>Message Not Seen Yet!!!</h4>
		{% endif %}
	
		</center>
		</div>



			<div id="footer" style="margin-top: 0px">
			<p><i><marquee>
			Reviews of the Colleges
			&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
			Reviews by the Students
			&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
			Reviews for the Students
			&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
			NIT Review System allows students from different NIT'S to give feedbacks on diffrent aspects
			and generates graph on that basis.
			&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
			<h7>Visit Often for latest rankings...</h7></i></marquee></p>
			</div>


  	</div>
  	</body>
</html>

qkd/templates/accounts/index.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    {% load static %}
   
    <title>Secure Communication Using Quantum Key Distribution</title>

    <link rel="stylesheet" type="text/css" href="{% static 'accounts/index.css' %}">
  </head>
  <body>
  	<div id="wrapper"style="width: 1350px; margin-left: -10px;" >

  		<div id="first" style="margin-top: -200px;width: 1350px;float: left;">
  			

  			<div id="div11" style="margin-top: 15px;">
				{% if user.is_authenticated %}
				<h1 >HELLO!!  &nbsp;   {{ user.first_name}} </h1>
				<p style="margin-top: 30px;font-size: 1.4em"><i>Communication – the human connection</i></p>
				{% else %}
				<h1 >Secure Communication Using Quantum Key Distribution</h1>
				<p style="margin-top: 30px;font-size: 1.4em"><i>Communication – the human connection</i></p>
				{% endif %}
  			</div>
  			</div>
  		<div id="menu" style="height: 50px;background-color: black;float: left;margin-top: -50px;width: 1350px;">
 		<div id="menu4" style="margin-top: 20px;background-color: black; width: 1350px">
			<ul>
			<li><a href="{% url 'home' %}">HOME</a></li>
			{% if user.is_authenticated %}

			{% else %}
			<li><a href="{% url 'accounts:register' %}">SIGN UP</a></li>
			{% endif %}
			{% if user.is_authenticated %}
			<li><a href="{% url 'accounts:logout' %}">LOGOUT</a></li>
			{% else %}
			<li><a href="{% url 'accounts:login' %}">LOGIN</a></li>
			{% endif %}

			</ul>
 		</div>
 		</div>
  		


		<div id = "div21" style="margin-top:200px; width: 1350px;">
		<div id = "content" style="margin-right:100px;min-height:360px;height:auto; width: 200px;  margin-top: 100px;">
			<center>
			{% if user.is_authenticated %}

			<table>
			{% for i in profiles %}
			<a href="{% url 'accounts:chat' user.id i.id%}">
			<button style="width:350px; height: 50px;">
			{{i.user}} </button>
			</a><br/>
			{% endfor %}
				
			</table>

			{% else %}

			{% endif %}
			</center>
		</div>
		</div>



			<div id="footer" style="margin-top: 0px; width:1310px;">
			<p><i><marquee>
			Communication – the human connection – is the key to personal and career success
			&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
			Conversation is king. Content is just something to talk about.
			&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
			<h7>Wise men speak because they have something to say; Fools because they have to say something</h7></i></marquee></p>
			</div>


  	</div>
  	</body>
</html>

qkd/templates/accounts/login.html
<html>
<head>

<style>
#he{
position:relative;
height:50px;
width:100%;
background-color:#28004d;
}
.title{
color:white;
font-size:40px;
font-family:lucida console;
text-align:center;
}



</style>

</head>
<body>
<div id='he'>

<p class='title' style="margin-top: 0px;">L O G I N</p>


</div>
</body>
</html><html>

<style>
body {
    background-image: url("/media/accounts/images/notebook.jpg");
    background-repeat: no-repeat;
    background-size: 1350px 650px;
    /*background-position: right top;*/
   
}


#box
{
height:20px;
width:500px;
margin-left:10px;
float:right;

}

#1
{
font-family:TIMES NEW ROMAN;
font-size:54;
color:RED;
margin-right:50px;
text-align:left;
}

#a{
	background-color:#28004d;
	height:70px;
	width:100%; 
	font-family:segoe script;
	color:#133926;
	font-style:bold;
	font-size:24px;
	color: white;
}
#b{
	margin-top:20px;
	margin-left:70px;
	margin-right:70px;

	border-radius:10px;

	padding:30px;

 
  max-width: 600px;
  opacity:0.95;
  background-color:#f2f2f2;
	
}
body, html {
  height: 100%;
}

* {
  box-sizing: border-box;
}


  input {
  width: 100%;
  padding: 15px;
  margin: 5px 0 22px 0;
  border: none;
  background:bfbfbf;
}

input:focus {
  background-color: #ddd;
  outline: none;
}
#bg{
  background-image: url("/media/accounts/images/notebook.jpg");
  height: 590px;

  
}

.btn {
  background-color: #80002a;
  color: white;
  padding: 16px 20px;
  border: none;
  cursor: pointer;
  width: 100%;
  opacity: 0.9;
}

.btn:hover {
  opacity: 1;
}
</style>
</head>
<body>
<div id="bg">
<div id="a"> <center>"Communication – the human connection" </center></div>
<center>
  
<div id="b" style="margin-top: 50px;">
      <form action="." method="POST">
            {% csrf_token %}
			{{form.as_p|safe}}
		<br>		
		<button type='submit' class="btn btn-info">Login</button>
        </form>

</div>
</div>
</center>
</body>

</html>

qkd/templates/accounts/message.html
{% if messages %}
	<div class="messages">
		<ul class="messages">
		    {% for message in messages %}
		    <li{% if message.tags %} class="{{ message.tags }} msg"{% endif %}>{{ message }}</li>
		    {% endfor %}
		</ul>
	</div>
	<style type="text/css">
		.msg{
			color:white;
		}
	</style>
{% endif %}

qkd/templates/accounts/messagesdisplay.html
<!DOCTYPE html>
<html>
<head>
	<title>Msgs</title>
</head>
<body>

<center><p><h1>{{msg}}</h1></p>
<button><a href="{% url 'home' %}" > HOME</a></button>
</center>
</body>
</html>